"""
THE MARLIN v2 — Parametric CAD source (CadQuery 2.x)  |  units: mm
====================================================================
Bottle-mounted folding MagSafe phone arm. Strap-based mount (no clamp
pads), hidden TPU anti-rotation liner, rigid load-bearing spine,
nested tapered folding arms, MagSafe head folds flat as the end cap.

MECHANICAL LOGIC ENCODED IN THIS MODEL
--------------------------------------
Strap routing (belt logic):
  * Fixed end of the 15 mm webbing loops through the spine's LOWER
    slot and is sewn back on itself (box-X stitch zone, modeled as
    stitch ridges) -> the spine is CAPTURED by the strap, not glued.
  * Free end wraps the bottle, enters the spine's UPPER slot from
    outside, doubles back, and is held by a low-profile slider
    (tri-glide). Tension range accommodates Ø83-95 mm bottles.
  * Two Ø3 rivets through webbing + TPU liner + spine lower tab lock
    the layers against creep/slip (backup to stitching).

Hidden grip liner:
  * 24 mm wide x 1.5 mm TPU liner bonded to the strap's inner face,
    WIDER than the 15 mm visible webbing, centered under the spine
    zone -> spreads the spine's bearing pressure onto the bottle and
    provides the anti-rotation friction couple.

Force path:
  phone -> MagSafe head -> arm3 -> pin3 -> arm2 -> pin1 -> arm1
  -> base pin (shear) -> spine clevis ears -> spine plate (bending
  over its 58 mm height) -> TPU liner (friction x strap tension)
  -> bottle wall; bottle mass = counterweight against tipping.

Hinge stack-up (every joint, outside -> in):
  shoulder-bolt head | outer wall | [friction washer | inner part |
  friction washer] | outer wall | lock nut.
  The nested-channel walls ARE the clevis: each smaller arm's end
  sits inside the larger arm's channel, so the pivot needs no extra
  knuckle hardware. PTFE friction washers (0.7 mm) set holding torque.

Fold kinematics (proves no collision):
  All three segments are modeled in the FOLDED nest. Every other
  configuration (extended / deployed) is generated by rotating the
  chain about the real pin axes, child-first. Pin axes are staggered
  12 mm in X and offset in Z so adjacent pins never intersect.
"""

import math, os
import cadquery as cq
from cadquery import exporters

# ============================================================
# PARAMETERS
# ============================================================
# ---- Strap ----
STRAP_W   = 15.0      # visible webbing width
STRAP_L   = 290.0     # flat webbing length
STRAP_T   = 2.0       # webbing thickness
PATCH_W   = 24.0      # hidden TPU liner width (wider than webbing)
PATCH_L   = 280.0     # liner length
PATCH_T   = 1.5       # liner thickness
SEW_LOOP  = 35.0      # fold-back sewn length at fixed end
WRAP_GAP  = 24.0      # degrees of opening in curled state
BOTTLE_R  = STRAP_L / (2 * math.pi)   # ~46.2 -> Ø92 bottle at nominal

# ---- Spine bracket (6061 alu or glass-filled nylon) ----
SPINE_T   = 4.0
SPINE_H   = 58.0
SPINE_W   = 24.0      # matches liner width
SLOT_W    = 17.0      # strap slots (webbing 15 + 2)
SLOT_H    = 3.0
EAR_R     = 9.8       # base hinge knuckle radius (spec 9.5-9.8)
EAR_T     = 3.0

# ---- Arms (nested channels; channel opens +Z in folded nest) ----
SEG_L     = 103.0     # pin-to-pin major span
WALL      = 2.0
CLEAR     = 0.7
A1_W, A1_D = 24.0, 14.0      # outer channel
A2_W, A2_D = 17.0, 11.0      # middle channel
A3_W, A3_D = 11.0,  8.0      # inner solid bar
END        = 10.0            # end margin beyond pin bores
STAG       = 12.0            # X-stagger between near-end pins

# ---- Hinge hardware ----
PIN_R     = 3.5       # spec 3.2-4.2
WASH_OD   = 12.0
WASH_T    = 0.7       # PTFE friction washer

# ---- MagSafe head ----
HEAD_S    = 50.0      # plate square
HEAD_T    = 4.0
RING_OD   = 56.0
RING_T    = 3.0
TAB_W     = 6.0

OUT = "/home/claude/marlin/out_v2"
os.makedirs(OUT, exist_ok=True)

# colors
C_WEB   = cq.Color(0.13, 0.18, 0.32)
C_TPU   = cq.Color(0.95, 0.55, 0.25)   # liner highlighted orange
C_AL    = cq.Color(0.66, 0.69, 0.74)
C_AL2   = cq.Color(0.52, 0.55, 0.62)
C_DARK  = cq.Color(0.22, 0.24, 0.29)
C_PIN   = cq.Color(0.35, 0.37, 0.42)
C_WASH  = cq.Color(0.90, 0.90, 0.85)
C_GHOST = cq.Color(0.55, 0.70, 0.85, 0.25)

# ============================================================
# FRAME: base hinge axis = Y-axis through origin.
# Arm chain modeled FOLDED, lying along +X, nest floor at z=-7.
# Pin axes (folded frame, XZ coords), all axes parallel to Y:
A0 = (0.0, 0.0)                    # spine <-> arm1
A1 = (SEG_L, 1.2)                  # arm1 <-> arm2   (z: nest stack-up)
A2 = (STAG, 2.4)                   # arm2 <-> arm3   (staggered 12 mm)
A3 = (SEG_L - STAG, 2.4)           # arm3 <-> head
# ============================================================

def ybore(wp, x, z, r=PIN_R, span=40):
    """Cut a Y-axis bore through everything at (x, z)."""
    drill = (cq.Workplane("XZ", origin=(x, span / 2, z))
             .circle(r).extrude(span))
    return wp.cut(drill)

def ycyl(x, z, y0, y1, r):
    """Y-axis cylinder from y0 to y1 at (x, z)."""
    return (cq.Workplane("XZ", origin=(x, -y0, z))   # XZ normal = -Y
            .circle(r).extrude(y1 - y0))

# ------------------------------------------------------------
# ARMS
# ------------------------------------------------------------
def channel(x0, x1, w_out, half_in, z_bot, z_top, floor):
    """Open-ended U-channel along X, opening +Z."""
    L, xm = x1 - x0, (x0 + x1) / 2
    body = (cq.Workplane("XY", origin=(xm, 0, z_bot))
            .rect(L, w_out).extrude(z_top - z_bot))
    cut = (cq.Workplane("XY", origin=(xm, 0, z_bot + floor))
           .rect(L + 2, half_in * 2).extrude(z_top - z_bot))
    return body.cut(cut)

# arm1: 24x14 channel, z -7..7, inner half-width 10, floor 2
arm1 = channel(-END, SEG_L + END, A1_W, 10.0, -7.0, 7.0, WALL)
arm1 = ybore(arm1, *A0); arm1 = ybore(arm1, *A1)

# arm2: 17x11 channel, z -4.3..6.7 (nests in arm1 with 0.7 clearance)
arm2 = channel(-END + 1, SEG_L + END - 1, A2_W, 6.5, -4.3, 6.7, WALL)
arm2 = ybore(arm2, *A1); arm2 = ybore(arm2, *A2)

# arm3: 11x8 solid bar, z -1.6..6.4, clevis slot at head end
arm3 = (cq.Workplane("XY", origin=((A2[0] - 9 + A3[0] + 9) / 2, 0, -1.6))
        .rect(A3[0] - A2[0] + 18, A3_W).extrude(8.0))
slot = (cq.Workplane("XY", origin=(A3[0] + 4, 0, -2.6))
        .rect(28, TAB_W + CLEAR).extrude(11))
arm3 = arm3.cut(slot)
arm3 = ybore(arm3, *A2); arm3 = ybore(arm3, *A3)

# ------------------------------------------------------------
# MAGSAFE HEAD (folds flat as the end cap of the stick)
# ------------------------------------------------------------
def magsafe_head():
    tab = (cq.Workplane("XZ", origin=(A3[0] + 9, TAB_W / 2, A3[1]))
           .slot2D(18, 7, 0).extrude(TAB_W)
           .translate((0, 0, 0)))
    tab = ybore(tab, *A3)
    plate = (cq.Workplane("YZ", origin=(SEG_L + END + 1, 0, A3[1]))
             .rect(HEAD_S, HEAD_S).extrude(HEAD_T)
             .edges("|X").fillet(8))
    ring = (cq.Workplane("YZ", origin=(SEG_L + END + 1 + HEAD_T, 0, A3[1]))
            .circle(RING_OD / 2).circle(RING_OD / 2 - 5).extrude(RING_T))
    disc = (cq.Workplane("YZ", origin=(SEG_L + END + 1 + HEAD_T, 0, A3[1]))
            .circle(RING_OD / 2 - 5).extrude(1.0))
    return tab.union(plate).union(ring).union(disc)

head = magsafe_head()

# ------------------------------------------------------------
# HARDWARE: shoulder pins + friction washers per joint
# ------------------------------------------------------------
def shoulder_pin(x, z, half):
    p = ycyl(x, z, -half, half, PIN_R - 0.05)
    p = p.union(ycyl(x, z, half, half + 2.2, PIN_R + 2.0))        # head
    p = p.union(ycyl(x, z, -half - 2.8, -half, PIN_R + 2.0))      # lock nut
    return p

def washer_pair(x, z, y_in):
    w1 = ycyl(x, z, y_in, y_in + WASH_T, WASH_OD / 2).cut(
         ycyl(x, z, y_in - .1, y_in + WASH_T + .1, PIN_R + 0.2))
    w2 = ycyl(x, z, -y_in - WASH_T, -y_in, WASH_OD / 2).cut(
         ycyl(x, z, -y_in - WASH_T - .1, -y_in + .1, PIN_R + 0.2))
    return w1.union(w2)

pin0 = shoulder_pin(*A0, 16.0)          # through spine ears (y +-15.7)
pin1 = shoulder_pin(*A1, A1_W / 2)      # through arm1 walls
pin2 = shoulder_pin(*A2, A2_W / 2)      # through arm2 walls
pin3 = shoulder_pin(*A3, A3_W / 2)      # through arm3 fork
wash0 = washer_pair(*A0, 12.0 + 0.05)   # ear face <-> arm1 wall
wash1 = washer_pair(*A1, 8.5 + 0.05)    # arm1 inner <-> arm2 outer
wash2 = washer_pair(*A2, 5.5 + 0.05)    # arm2 inner <-> arm3 side
wash3 = washer_pair(*A3, 3.35)          # arm3 fork <-> head tab

# ------------------------------------------------------------
# SPINE BRACKET (static; ears straddle arm1 at the base axis)
# ------------------------------------------------------------
def spine_bracket():
    plate = (cq.Workplane("XY", origin=(-6.0, 0, -SPINE_H))
             .rect(SPINE_T, SPINE_W).extrude(SPINE_H - 6))
    wing = (cq.Workplane("XY", origin=(-6.0, 0, -16))
            .rect(SPINE_T, 2 * (12.7 + EAR_T)).extrude(10))
    ear_p = ycyl(*A0, 12.7, 12.7 + EAR_T, EAR_R)
    ear_n = ycyl(*A0, -12.7 - EAR_T, -12.7, EAR_R)
    neck_p = (cq.Workplane("XY", origin=(-6.0, 12.7 + EAR_T / 2, -16))
              .rect(SPINE_T, EAR_T).extrude(16))
    neck_n = (cq.Workplane("XY", origin=(-6.0, -12.7 - EAR_T / 2, -16))
              .rect(SPINE_T, EAR_T).extrude(16))
    s = plate.union(wing).union(ear_p).union(ear_n).union(neck_p).union(neck_n)
    # strap slots: lower (fixed sewn end) + upper (adjustable return)
    for zc in (-46.0, -18.0):
        s = s.cut(cq.Workplane("XY", origin=(-6.0, 0, zc - SLOT_H / 2))
                  .rect(SPINE_T + 2, SLOT_W).extrude(SLOT_H))
    # rivet bores through plate (match strap + liner)
    for yy in (6.0, -6.0):
        s = s.cut(cq.Workplane("YZ", origin=(-9, yy, -32)).circle(1.5).extrude(6))
    s = ybore(s, *A0)
    return s

spine = spine_bracket()

# ------------------------------------------------------------
# STRAP — FLAT STATE (manufacturing layout)
# ------------------------------------------------------------
def strap_flat():
    web = (cq.Workplane("XY").slot2D(STRAP_L - STRAP_W, STRAP_W, 0)
           .extrude(STRAP_T))
    x_fix = -STRAP_L / 2 + SEW_LOOP / 2 + 4
    loop = (cq.Workplane("XY", origin=(x_fix, 0, STRAP_T))
            .rect(SEW_LOOP, STRAP_W).extrude(STRAP_T))           # fold-back
    stitches = None
    for i in range(3):                                            # box-X zone
        st = (cq.Workplane("XY", origin=(x_fix - 10 + i * 10, 0, 2 * STRAP_T))
              .rect(1.2, STRAP_W - 2).extrude(0.5))
        stitches = st if stitches is None else stitches.union(st)
    web2 = web.union(loop)
    for yy in (4.0, -4.0):                                        # rivet holes
        web2 = web2.cut(cq.Workplane("XY", origin=(x_fix, yy, -1))
                        .circle(1.5).extrude(8))
    patch = (cq.Workplane("XY", origin=(0, 0, -PATCH_T))
             .slot2D(PATCH_L - PATCH_W, PATCH_W, 0).extrude(PATCH_T))
    slider = (cq.Workplane("XY", origin=(STRAP_L / 2 - 40, 0, -1))
              .rect(16, STRAP_W + 5).extrude(STRAP_T + 2)
              .cut(cq.Workplane("XY", origin=(STRAP_L / 2 - 44, 0, -2))
                   .rect(5, STRAP_W + 1).extrude(8))
              .cut(cq.Workplane("XY", origin=(STRAP_L / 2 - 36, 0, -2))
                   .rect(5, STRAP_W + 1).extrude(8)))
    return web2, stitches, patch, slider

webF, stitchF, patchF, sliderF = strap_flat()

# ------------------------------------------------------------
# STRAP — CURLED STATE (around Ø92 bottle), axis = Z
# ------------------------------------------------------------
def band(w, t, r_in, sweep, start_deg):
    b = (cq.Workplane("XZ").center(r_in + t / 2, 0).rect(t, w)
         .revolve(sweep, (-(r_in + t / 2), 0, 0), (-(r_in + t / 2), 1, 0)))
    return b.rotate((0, 0, 0), (0, 0, 1), start_deg)

def strap_curled(center=(0, 0, 0)):
    sweep = 360 - WRAP_GAP
    p = band(PATCH_W, PATCH_T, BOTTLE_R, sweep * PATCH_L / STRAP_L,
             WRAP_GAP / 2 + 4)
    w = band(STRAP_W, STRAP_T, BOTTLE_R + PATCH_T, sweep, WRAP_GAP / 2)
    mv = lambda s: s.translate(center)
    return mv(w), mv(p)

webC, patchC = strap_curled()

# ------------------------------------------------------------
# FORWARD KINEMATICS  (child-first rotations about folded-frame axes)
# ------------------------------------------------------------
def rotY(shape, ax, ang):
    if ang == 0:
        return shape
    return shape.rotate((ax[0], -100, ax[1]), (ax[0], 100, ax[1]), ang)

def pose(t0, t1, t2, t3):
    """Return dict of posed arm-chain solids for fold angles (deg)."""
    g_head  = [("head", head, C_DARK), ("pin3", pin3, C_PIN)]
    g_arm3  = [("arm3", arm3, C_AL2), ("wash3", wash3, C_WASH),
               ("pin2", pin2, C_PIN)]
    g_arm2  = [("arm2", arm2, C_AL), ("wash2", wash2, C_WASH),
               ("pin1", pin1, C_PIN)]
    g_arm1  = [("arm1", arm1, C_AL), ("wash1", wash1, C_WASH),
               ("pin0", pin0, C_PIN), ("wash0", wash0, C_WASH)]
    out = []
    for nm, s, c in g_head:
        out.append((nm, rotY(rotY(rotY(rotY(s, A3, t3), A2, t2), A1, t1), A0, t0), c))
    for nm, s, c in g_arm3:
        out.append((nm, rotY(rotY(rotY(s, A2, t2), A1, t1), A0, t0), c))
    for nm, s, c in g_arm2:
        out.append((nm, rotY(rotY(s, A1, t1), A0, t0), c))
    for nm, s, c in g_arm1:
        out.append((nm, rotY(s, A0, t0), c))
    return out

def save(asm, name):
    asm.save(f"{OUT}/{name}.step")
    exporters.export(asm.toCompound(), f"{OUT}/{name}.stl")
    print("  saved", name)

def asm_of(parts, name, extra=()):
    a = cq.Assembly(name=name)
    for nm, s, c in list(extra) + parts:
        a.add(s, name=nm, color=c)
    save(a, name)

bottle = (cq.Workplane("XY", origin=(-(9.5 + BOTTLE_R), 0, -130))
          .circle(BOTTLE_R).extrude(200))   # reference body
ring_c = (-(9.5 + BOTTLE_R), 0, -32)

print("Exporting configurations...")

# 01 — strap flat
asm_of([("webbing", webF, C_WEB), ("stitches", stitchF, C_WASH),
        ("tpu_liner", patchF, C_TPU), ("slider", sliderF, C_DARK)],
       "01_strap_flat")

# 02 — strap curled
asm_of([("webbing", webC, C_WEB), ("tpu_liner", patchC, C_TPU)],
       "02_strap_curled")

# 03 — arm extended straight (+ open head)
asm_of(pose(0, 180, 180, -90) + [("spine", spine, C_DARK)],
       "03_arm_extended")

# 04 — arm folded nested stick (head caps the end)
asm_of(pose(-90, 0, 0, 0) + [("spine", spine, C_DARK)],
       "04_arm_folded_stick")

# 05 — full assembly, deployed zig-zag on bottle
webC2, patchC2 = strap_curled(ring_c)
asm_of(pose(-62, -157, -152, -55) +
       [("spine", spine, C_DARK)],
       "05_full_assembly_deployed",
       extra=[("bottle_ref", bottle, C_GHOST),
              ("webbing", webC2, C_WEB), ("tpu_liner", patchC2, C_TPU)])

# 06 — full assembly, folded stick on bottle
asm_of(pose(-90, 0, 0, 0) + [("spine", spine, C_DARK)],
       "06_full_assembly_folded",
       extra=[("bottle_ref", bottle, C_GHOST),
              ("webbing", webC2, C_WEB), ("tpu_liner", patchC2, C_TPU)])

# 07 — hinge stack-up, exploded along pin axis (joint 1)
a = cq.Assembly(name="07_hinge_stackup_exploded")
a.add(arm1, name="arm1_clevis_walls", color=C_AL)
a.add(wash1.translate((0, 22, 0)), name="friction_washers", color=C_WASH)
a.add(arm2.translate((0, 48, 0)), name="arm2_tongue", color=C_AL)
a.add(pin1.translate((0, 80, 0)), name="shoulder_pin_and_nut", color=C_PIN)
save(a, "07_hinge_stackup_exploded")

print("DONE")
